/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crestron_txrxservice_GstreamOut */

///////////////////////////////////////////////////////////////////////////////
/* JNI signatures
* Type     Character
* boolean      Z
* byte         B
* char         C
* double       D
* float        F
* int          I
* long         J
* object       L
* short        S
* void         V
* array        [
*/
///////////////////////////////////////////////////////////////////////////////

#ifndef _Included_com_crestron_txrxservice_GstreamOut
#define _Included_com_crestron_txrxservice_GstreamOut
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_crestron_txrxservice_GstreamOut
 * Method:    nativeSetRtspPort
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_GstreamOut_nativeSetRtspPort
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_crestron_txrxservice_GstreamOut
 * Method:    nativeSet_Res_x
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_GstreamOut_nativeSet_1Res_1x
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_crestron_txrxservice_GstreamOut
 * Method:    nativeSet_Res_y
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_GstreamOut_nativeSet_1Res_1y
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_crestron_txrxservice_GstreamOut
 * Method:    nativeSet_FrameRate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_GstreamOut_nativeSet_1FrameRate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_crestron_txrxservice_GstreamOut
 * Method:    nativeSet_Bitrate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_GstreamOut_nativeSet_1Bitrate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_crestron_txrxservice_GstreamOut
 * Method:    nativeSet_IFrameInterval
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_GstreamOut_nativeSet_1IFrameInterval
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
