/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header file for WbsStreamIn */

///////////////////////////////////////////////////////////////////////////////
/* JNI signatures
* Type     Character
* boolean      Z
* byte         B
* char         C
* double       D
* float        F
* int          I
* long         J
* object       L
* short        S
* void         V
* array        [
*/
///////////////////////////////////////////////////////////////////////////////

#ifndef __WbsStreamIn_H__
#define __WbsStreamIn_H__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     		WbsStreamIn
 * Method:    		nativeSurfaceInit
 * Signature: 		(Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeSurfaceInit(JNIEnv *, jobject, jobject, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeSurfaceFinalize
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeSurfaceFinalize(JNIEnv *, jobject, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeInit
 * Signature: 		()V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeInit(JNIEnv *, jobject);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeFinalize
 * Signature: 		()V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeFinalize(JNIEnv *, jobject);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativePlay
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativePlay(JNIEnv *, jobject, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeStop
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeStop(JNIEnv *, jobject, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativePause
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativePause(JNIEnv *, jobject, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeUnpause
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeUnpause(JNIEnv *, jobject, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeSetUrl
 * Signature: 		(Ljava/lang/string; I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeSetUrl(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeSetLogLevel
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeSetLogLevel(JNIEnv *, jobject, jint);

///////////////////////////////////////////////////////////////////////////////
eStreamState nativeGetCurrentStreamState(jint);

#ifdef __cplusplus
}
#endif
#endif
