/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header file for WbsStreamIn */

///////////////////////////////////////////////////////////////////////////////
/* JNI signatures
* Type     Character
* boolean      Z
* byte         B
* char         C
* double       D
* float        F
* int          I
* long         J
* object       L
* short        S
* void         V
* array        [
*/
///////////////////////////////////////////////////////////////////////////////

#ifndef __WbsStreamIn_H__
#define __WbsStreamIn_H__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     		WbsStreamIn
 * Method:    		nativeSetUrl
 * Signature: 		(Ljava/lang/string; I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeSetUrl(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     		WbsStreamIn
 * Method:    		nativeSetLogLevel
 * Signature: 		(I)V
 */
JNIEXPORT void JNICALL Java_com_crestron_txrxservice_WbsStreamIn_nativeSetLogLevel(JNIEnv *env, jobject thiz, jint logLevel);

///////////////////////////////////////////////////////////////////////////////
eStreamState nativeGetCurrentStreamState(jint);
void csio_send_stats (uint64_t, int, uint64_t, int, uint16_t);
int csio_SendVideoPlayingStatusMessage(unsigned int, eStreamState);
int csio_SendVideoSourceParams(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int);

#ifdef __cplusplus
}
#endif
#endif
